portalarchitects/skysync-cli

- samples/powershell/basic-nfs-to-box-copy-job/skysync-cli-sample-create-job-01.ps1
- src/commands/jobs/add.ts
…on block to support scheduling and personal_drive jobs
> SF-2211: modify job creation to accept json for the entire job creati

- src/sdk/models/transfers.ts
I'm at a loss for how to test this. I don't see where this code is actually being used and was unable to debug into it. Unit tests are successfully running and the job related commands all still work. Any ideas are appreciated.
> SF-2434 - Fixed transfer options permissions_import to match new format

- src/commands/diagnostics/fiddler/uninstall-certs.ts
- src/commands/diagnostics/fiddler/util.ts
> SF-4292 - Fixed issues with uninstall-certs command

- package-lock.json
- package.json
- src/sdk/client.ts
- src/sdk/models/transfers.ts
- src/sdk/resources/index.ts
- src/sdk/resources/transferPermissions.ts
Adding necessary components for TransferPermissions to be exposed through the CLI
> Adding necessary components for TransferPermissions to be exposed through the CLI

- src/sdk/cancellation-token.ts
Fix recursive property `isCancelled`
> Fix CancellationToken.isCancelled

- src/sdk/models/jobs.ts
Adding JobScheduleType enumeration to JobSchedule to accommodate changes to SF-5440
> Adding JobScheduleType to JobSchedule to accommodate changes to SF-5440

- src/sdk/models/jobs.ts
Removing job schedule type from CLI per discussion with Rebecca
> Removing job schedule type from CLI

- package-lock.json
- package.json
- A few patch upgrades to match versions that will be referenced by design system upgrades
- Also a couple minor upgrades that are new-ish
Note that 1 test (formatDate should format days-distant dates) fails for me locally but passes in Azure.
> Sf-6913 | Catch up to future design system upgrades

- azure-pipelines.yml
- package.json
- src/sdk/formatting/formatDate.ts
Bumping Azure Node version to 14.
> SF-6911: Upgrade Node to latest LTS v14

- src/sdk/models/transfers.ts
related: https://github.com/portalarchitects/skysync-vnext/pull/2875
> SF-7686 | Add rendition to TransferOptions and create RenditionType enum

- src/sdk/resources/personalDriveExceptions.ts
- src/sdk/resources/personalDriveMatches.ts
Sorry, there is one more use case for exception/exclusion import.
> SF-8154 | Added file import to personal_drives exceptions and matches

- src/sdk/models/connections.ts
Leaving as draft until after hotfix is merged
> SF-8330 | Updated PromptAttribute interface with some missing values

- src/sdk/client.ts
- src/sdk/models/entityTypes.ts
- src/sdk/resources/entityTypeDictionaries.ts
- src/sdk/resources/entityTypeDictionaryElements.ts
- src/sdk/resources/entityTypes.ts
- src/sdk/resources/index.ts
Adding support for entity type dictionaries and entity type dictionary terms.
> ACT-1091: Add entity type dictionary/elements support

- src/sdk/resources/policyTrackingGroups.ts
Added clone function to PolicyTrackingGroupsResource.
> ACT-1164 | UI | Policy Editor | Add edit options to tracking group actions menu

- src/commands/users/list.ts
- Changed active property to status
> CL99-63 | List users not filtering by active

- src/sdk/models/entityTypes.ts
- src/sdk/resources/policies.ts
- src/sdk/resources/policyTrackingGroups.ts
Add entity type assignment resources
> ACT-1524 | Add entity type assignment resources

- src/sdk/resources/policies.ts
- src/sdk/resources/policyTrackingGroups.ts
Updating Entity Type Assignment Endpoints from Patch to Post
> ACT-1524-b | Updating Entity Type Assignment Endpoints from Patch to Post

- src/sdk/resources/entityTypeDictionaryElements.ts
Add method for importing keywords on existing dictionary.
> ACT-1392: Add CSV file import method for keywords

- src/sdk/client.ts
- src/sdk/models/policies.ts
- src/sdk/resources/index.ts
- src/sdk/resources/policyActionTypes.ts
- src/sdk/resources/policyActions.ts
Added new PolicyActionsResource and associated PolicyAction model so the app can retrieve the available actions from the `/v1/policies/actions` endpoint.
> ACT-1169 | UI | Policy Editor | Allow managing list of actions

- src/sdk/models/policies.ts
Added PolicyActionTypeId enum.
> ACT-1486 | UX | Policy Editor - Manual intervention on actions

- src/sdk/models/policies.ts
Adding priority to PolicyTrackingGroupRule
> ACT-1621 | Updating PolicyTrackingGroupRule to be a Prioritized Entity

- src/commands/connections/stats.ts
- src/sdk/client.ts
- src/sdk/models/connections.ts
- src/sdk/resources/connections.ts
Exposes new connections stats command. Backend work in this [PR](https://github.com/portalarchitects/skysync-vnext/pull/3426).
> Sf-8907 | Solution for getting a File and Folder Count for a single connection/data source

- src/sdk/models/extensions.ts
Adding optional configuration prop to Extension model
> ACT-1873 | Adding optional configuration prop to Extension model

- src/sdk/client.ts
- src/sdk/models/policyStatistics.ts
- src/sdk/resources/index.ts
- src/sdk/resources/policyStatisticsSummary.ts
don't merge, not sure if this is correct - yet.
> ACT-1098 | statistics summary resource

- src/sdk/resources/extensions.ts
Add GET Configuration endpoint to Extensions resource
> ACT-1873 | Add GET Configuration endpoint to Extensions resource

- src/sdk/client.ts
- src/sdk/models/index.ts
- src/sdk/models/performance.ts
- src/sdk/resources/index.ts
- src/sdk/resources/performance.ts
- src/sdk/resources/resource.test.ts
Creating as draft PR placeholder while testing changes
> SF-7795 | Added SDK support for calling new performance controller

- src/sdk/models/diagnostics.ts
> sf-9045 | Ability to change the logging level within the UI

- src/commands/performance.ts
- src/commands/performance/parallel_writes.ts
- src/commands/performance/parallel_writes/show.ts
- src/commands/performance/parallel_writes/update.ts
- src/commands/performance/parallel_writes/util.ts
Back end changes in this [PR](https://github.com/portalarchitects/skysync-vnext/pull/3484)
> SF-7795 | Added new CLI commands for managing parallel write configuration

- src/sdk/formatting/formatCurrency.test.ts
- src/sdk/formatting/formatCurrency.ts
- src/sdk/formatting/formatNumber.ts
- src/sdk/formatting/index.ts
Add formatCurrency to DataFormatter
> ACT-1109 | Add formatCurrency to DataFormatter

- src/sdk/models/notifications.ts
- src/sdk/resources/notifications.ts
Add CLI support for retrieving SMTP configuration
> ACT-1851 | Add CLI support for retrieving SMTP configuration

- src/sdk/models/policies.ts
Add requires_location to PolicyTrackingGroupAction
> ACT-1926 | Add requires_location to PolicyTrackingGroupAction

- src/sdk/resources/entityTypes.ts
Adds clone method to resource.
> ACT-2593 | Action menu item ( ellipsis menu ) to duplicate entity type 

- src/sdk/models/entityTypes.ts
So far this is the only change I think is needed but keeping in draft for now.
AC changed to include changes to text for Upload sample and Evaluate item dialogs.
> ACT-2695 | Entity Type Enhancement | Support for Negative Keyword Lists

- src/sdk/models/entityTypes.ts
Added dictionary search options.
> ACT-2334 ACT-3681 | Keyword & Negative Proximity Frontend

- src/sdk/client.ts
- src/sdk/models/policies.ts
- src/sdk/resources/index.ts
- src/sdk/resources/policyLocationActions.ts
- src/sdk/resources/policyLocationRules.ts
Updates related to allowing location-specific rules to be configured. These changes are used in [this vnext PR](https://github.com/portalarchitects/skysync-vnext/pull/4107).
> ACT-3271 | UI | Data source specific placeholder configuration
